/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardUnitsRouteImport } from './routes/dashboard/units'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardExercisesRouteImport } from './routes/dashboard/exercises'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard/courses'
import { Route as DashboardExercisesIndexRouteImport } from './routes/dashboard/exercises/index'
import { Route as DashboardCoursesIndexRouteImport } from './routes/dashboard/courses/index'
import { Route as DashboardSettingsCustomizationRouteImport } from './routes/dashboard/settings/customization'
import { Route as DashboardSettingsAccountRouteImport } from './routes/dashboard/settings/account'
import { Route as DashboardExercisesAddRouteImport } from './routes/dashboard/exercises/add'
import { Route as DashboardCoursesAddRouteImport } from './routes/dashboard/courses/add'
import { Route as DashboardExercisesExerciseIdIndexRouteImport } from './routes/dashboard/exercises/$exerciseId/index'
import { Route as DashboardUnitsUnitIdEditRouteImport } from './routes/dashboard/units/$unitId/edit'
import { Route as DashboardCoursesCourseIdViewRouteImport } from './routes/dashboard/courses/$courseId.view'
import { Route as DashboardCoursesCourseIdUpdateRouteImport } from './routes/dashboard/courses/$courseId.update'
import { Route as DashboardCoursesCourseIdEditIndexRouteImport } from './routes/dashboard/courses/$courseId/edit/index'
import { Route as DashboardExercisesExerciseIdEditCurriculumRouteImport } from './routes/dashboard/exercises/$exerciseId/edit/curriculum'
import { Route as DashboardCoursesCourseIdEditCurriculumRouteImport } from './routes/dashboard/courses/$courseId/edit/curriculum'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUnitsRoute = DashboardUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExercisesRoute = DashboardExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExercisesIndexRoute = DashboardExercisesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardExercisesRoute,
} as any)
const DashboardCoursesIndexRoute = DashboardCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCoursesRoute,
} as any)
const DashboardSettingsCustomizationRoute =
  DashboardSettingsCustomizationRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardExercisesAddRoute = DashboardExercisesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DashboardExercisesRoute,
} as any)
const DashboardCoursesAddRoute = DashboardCoursesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DashboardCoursesRoute,
} as any)
const DashboardExercisesExerciseIdIndexRoute =
  DashboardExercisesExerciseIdIndexRouteImport.update({
    id: '/$exerciseId/',
    path: '/$exerciseId/',
    getParentRoute: () => DashboardExercisesRoute,
  } as any)
const DashboardUnitsUnitIdEditRoute =
  DashboardUnitsUnitIdEditRouteImport.update({
    id: '/$unitId/edit',
    path: '/$unitId/edit',
    getParentRoute: () => DashboardUnitsRoute,
  } as any)
const DashboardCoursesCourseIdViewRoute =
  DashboardCoursesCourseIdViewRouteImport.update({
    id: '/$courseId/view',
    path: '/$courseId/view',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)
const DashboardCoursesCourseIdUpdateRoute =
  DashboardCoursesCourseIdUpdateRouteImport.update({
    id: '/$courseId/update',
    path: '/$courseId/update',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)
const DashboardCoursesCourseIdEditIndexRoute =
  DashboardCoursesCourseIdEditIndexRouteImport.update({
    id: '/$courseId/edit/',
    path: '/$courseId/edit/',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)
const DashboardExercisesExerciseIdEditCurriculumRoute =
  DashboardExercisesExerciseIdEditCurriculumRouteImport.update({
    id: '/$exerciseId/edit/curriculum',
    path: '/$exerciseId/edit/curriculum',
    getParentRoute: () => DashboardExercisesRoute,
  } as any)
const DashboardCoursesCourseIdEditCurriculumRoute =
  DashboardCoursesCourseIdEditCurriculumRouteImport.update({
    id: '/$courseId/edit/curriculum',
    path: '/$courseId/edit/curriculum',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/exercises': typeof DashboardExercisesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/units': typeof DashboardUnitsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/add': typeof DashboardCoursesAddRoute
  '/dashboard/exercises/add': typeof DashboardExercisesAddRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/customization': typeof DashboardSettingsCustomizationRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/exercises/': typeof DashboardExercisesIndexRoute
  '/dashboard/courses/$courseId/update': typeof DashboardCoursesCourseIdUpdateRoute
  '/dashboard/courses/$courseId/view': typeof DashboardCoursesCourseIdViewRoute
  '/dashboard/units/$unitId/edit': typeof DashboardUnitsUnitIdEditRoute
  '/dashboard/exercises/$exerciseId/': typeof DashboardExercisesExerciseIdIndexRoute
  '/dashboard/courses/$courseId/edit/curriculum': typeof DashboardCoursesCourseIdEditCurriculumRoute
  '/dashboard/exercises/$exerciseId/edit/curriculum': typeof DashboardExercisesExerciseIdEditCurriculumRoute
  '/dashboard/courses/$courseId/edit/': typeof DashboardCoursesCourseIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/units': typeof DashboardUnitsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/courses/add': typeof DashboardCoursesAddRoute
  '/dashboard/exercises/add': typeof DashboardExercisesAddRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/customization': typeof DashboardSettingsCustomizationRoute
  '/dashboard/courses': typeof DashboardCoursesIndexRoute
  '/dashboard/exercises': typeof DashboardExercisesIndexRoute
  '/dashboard/courses/$courseId/update': typeof DashboardCoursesCourseIdUpdateRoute
  '/dashboard/courses/$courseId/view': typeof DashboardCoursesCourseIdViewRoute
  '/dashboard/units/$unitId/edit': typeof DashboardUnitsUnitIdEditRoute
  '/dashboard/exercises/$exerciseId': typeof DashboardExercisesExerciseIdIndexRoute
  '/dashboard/courses/$courseId/edit/curriculum': typeof DashboardCoursesCourseIdEditCurriculumRoute
  '/dashboard/exercises/$exerciseId/edit/curriculum': typeof DashboardExercisesExerciseIdEditCurriculumRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/exercises': typeof DashboardExercisesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/units': typeof DashboardUnitsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/add': typeof DashboardCoursesAddRoute
  '/dashboard/exercises/add': typeof DashboardExercisesAddRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/customization': typeof DashboardSettingsCustomizationRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/exercises/': typeof DashboardExercisesIndexRoute
  '/dashboard/courses/$courseId/update': typeof DashboardCoursesCourseIdUpdateRoute
  '/dashboard/courses/$courseId/view': typeof DashboardCoursesCourseIdViewRoute
  '/dashboard/units/$unitId/edit': typeof DashboardUnitsUnitIdEditRoute
  '/dashboard/exercises/$exerciseId/': typeof DashboardExercisesExerciseIdIndexRoute
  '/dashboard/courses/$courseId/edit/curriculum': typeof DashboardCoursesCourseIdEditCurriculumRoute
  '/dashboard/exercises/$exerciseId/edit/curriculum': typeof DashboardExercisesExerciseIdEditCurriculumRoute
  '/dashboard/courses/$courseId/edit/': typeof DashboardCoursesCourseIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/courses'
    | '/dashboard/exercises'
    | '/dashboard/settings'
    | '/dashboard/units'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/courses/add'
    | '/dashboard/exercises/add'
    | '/dashboard/settings/account'
    | '/dashboard/settings/customization'
    | '/dashboard/courses/'
    | '/dashboard/exercises/'
    | '/dashboard/courses/$courseId/update'
    | '/dashboard/courses/$courseId/view'
    | '/dashboard/units/$unitId/edit'
    | '/dashboard/exercises/$exerciseId/'
    | '/dashboard/courses/$courseId/edit/curriculum'
    | '/dashboard/exercises/$exerciseId/edit/curriculum'
    | '/dashboard/courses/$courseId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/settings'
    | '/dashboard/units'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/courses/add'
    | '/dashboard/exercises/add'
    | '/dashboard/settings/account'
    | '/dashboard/settings/customization'
    | '/dashboard/courses'
    | '/dashboard/exercises'
    | '/dashboard/courses/$courseId/update'
    | '/dashboard/courses/$courseId/view'
    | '/dashboard/units/$unitId/edit'
    | '/dashboard/exercises/$exerciseId'
    | '/dashboard/courses/$courseId/edit/curriculum'
    | '/dashboard/exercises/$exerciseId/edit/curriculum'
    | '/dashboard/courses/$courseId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/courses'
    | '/dashboard/exercises'
    | '/dashboard/settings'
    | '/dashboard/units'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/courses/add'
    | '/dashboard/exercises/add'
    | '/dashboard/settings/account'
    | '/dashboard/settings/customization'
    | '/dashboard/courses/'
    | '/dashboard/exercises/'
    | '/dashboard/courses/$courseId/update'
    | '/dashboard/courses/$courseId/view'
    | '/dashboard/units/$unitId/edit'
    | '/dashboard/exercises/$exerciseId/'
    | '/dashboard/courses/$courseId/edit/curriculum'
    | '/dashboard/exercises/$exerciseId/edit/curriculum'
    | '/dashboard/courses/$courseId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/units': {
      id: '/dashboard/units'
      path: '/units'
      fullPath: '/dashboard/units'
      preLoaderRoute: typeof DashboardUnitsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exercises': {
      id: '/dashboard/exercises'
      path: '/exercises'
      fullPath: '/dashboard/exercises'
      preLoaderRoute: typeof DashboardExercisesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exercises/': {
      id: '/dashboard/exercises/'
      path: '/'
      fullPath: '/dashboard/exercises/'
      preLoaderRoute: typeof DashboardExercisesIndexRouteImport
      parentRoute: typeof DashboardExercisesRoute
    }
    '/dashboard/courses/': {
      id: '/dashboard/courses/'
      path: '/'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof DashboardCoursesIndexRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/settings/customization': {
      id: '/dashboard/settings/customization'
      path: '/customization'
      fullPath: '/dashboard/settings/customization'
      preLoaderRoute: typeof DashboardSettingsCustomizationRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/account': {
      id: '/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/exercises/add': {
      id: '/dashboard/exercises/add'
      path: '/add'
      fullPath: '/dashboard/exercises/add'
      preLoaderRoute: typeof DashboardExercisesAddRouteImport
      parentRoute: typeof DashboardExercisesRoute
    }
    '/dashboard/courses/add': {
      id: '/dashboard/courses/add'
      path: '/add'
      fullPath: '/dashboard/courses/add'
      preLoaderRoute: typeof DashboardCoursesAddRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/exercises/$exerciseId/': {
      id: '/dashboard/exercises/$exerciseId/'
      path: '/$exerciseId'
      fullPath: '/dashboard/exercises/$exerciseId/'
      preLoaderRoute: typeof DashboardExercisesExerciseIdIndexRouteImport
      parentRoute: typeof DashboardExercisesRoute
    }
    '/dashboard/units/$unitId/edit': {
      id: '/dashboard/units/$unitId/edit'
      path: '/$unitId/edit'
      fullPath: '/dashboard/units/$unitId/edit'
      preLoaderRoute: typeof DashboardUnitsUnitIdEditRouteImport
      parentRoute: typeof DashboardUnitsRoute
    }
    '/dashboard/courses/$courseId/view': {
      id: '/dashboard/courses/$courseId/view'
      path: '/$courseId/view'
      fullPath: '/dashboard/courses/$courseId/view'
      preLoaderRoute: typeof DashboardCoursesCourseIdViewRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/courses/$courseId/update': {
      id: '/dashboard/courses/$courseId/update'
      path: '/$courseId/update'
      fullPath: '/dashboard/courses/$courseId/update'
      preLoaderRoute: typeof DashboardCoursesCourseIdUpdateRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/courses/$courseId/edit/': {
      id: '/dashboard/courses/$courseId/edit/'
      path: '/$courseId/edit'
      fullPath: '/dashboard/courses/$courseId/edit/'
      preLoaderRoute: typeof DashboardCoursesCourseIdEditIndexRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/exercises/$exerciseId/edit/curriculum': {
      id: '/dashboard/exercises/$exerciseId/edit/curriculum'
      path: '/$exerciseId/edit/curriculum'
      fullPath: '/dashboard/exercises/$exerciseId/edit/curriculum'
      preLoaderRoute: typeof DashboardExercisesExerciseIdEditCurriculumRouteImport
      parentRoute: typeof DashboardExercisesRoute
    }
    '/dashboard/courses/$courseId/edit/curriculum': {
      id: '/dashboard/courses/$courseId/edit/curriculum'
      path: '/$courseId/edit/curriculum'
      fullPath: '/dashboard/courses/$courseId/edit/curriculum'
      preLoaderRoute: typeof DashboardCoursesCourseIdEditCurriculumRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
  }
}

interface DashboardCoursesRouteChildren {
  DashboardCoursesAddRoute: typeof DashboardCoursesAddRoute
  DashboardCoursesIndexRoute: typeof DashboardCoursesIndexRoute
  DashboardCoursesCourseIdUpdateRoute: typeof DashboardCoursesCourseIdUpdateRoute
  DashboardCoursesCourseIdViewRoute: typeof DashboardCoursesCourseIdViewRoute
  DashboardCoursesCourseIdEditCurriculumRoute: typeof DashboardCoursesCourseIdEditCurriculumRoute
  DashboardCoursesCourseIdEditIndexRoute: typeof DashboardCoursesCourseIdEditIndexRoute
}

const DashboardCoursesRouteChildren: DashboardCoursesRouteChildren = {
  DashboardCoursesAddRoute: DashboardCoursesAddRoute,
  DashboardCoursesIndexRoute: DashboardCoursesIndexRoute,
  DashboardCoursesCourseIdUpdateRoute: DashboardCoursesCourseIdUpdateRoute,
  DashboardCoursesCourseIdViewRoute: DashboardCoursesCourseIdViewRoute,
  DashboardCoursesCourseIdEditCurriculumRoute:
    DashboardCoursesCourseIdEditCurriculumRoute,
  DashboardCoursesCourseIdEditIndexRoute:
    DashboardCoursesCourseIdEditIndexRoute,
}

const DashboardCoursesRouteWithChildren =
  DashboardCoursesRoute._addFileChildren(DashboardCoursesRouteChildren)

interface DashboardExercisesRouteChildren {
  DashboardExercisesAddRoute: typeof DashboardExercisesAddRoute
  DashboardExercisesIndexRoute: typeof DashboardExercisesIndexRoute
  DashboardExercisesExerciseIdIndexRoute: typeof DashboardExercisesExerciseIdIndexRoute
  DashboardExercisesExerciseIdEditCurriculumRoute: typeof DashboardExercisesExerciseIdEditCurriculumRoute
}

const DashboardExercisesRouteChildren: DashboardExercisesRouteChildren = {
  DashboardExercisesAddRoute: DashboardExercisesAddRoute,
  DashboardExercisesIndexRoute: DashboardExercisesIndexRoute,
  DashboardExercisesExerciseIdIndexRoute:
    DashboardExercisesExerciseIdIndexRoute,
  DashboardExercisesExerciseIdEditCurriculumRoute:
    DashboardExercisesExerciseIdEditCurriculumRoute,
}

const DashboardExercisesRouteWithChildren =
  DashboardExercisesRoute._addFileChildren(DashboardExercisesRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute
  DashboardSettingsCustomizationRoute: typeof DashboardSettingsCustomizationRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
  DashboardSettingsCustomizationRoute: DashboardSettingsCustomizationRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardUnitsRouteChildren {
  DashboardUnitsUnitIdEditRoute: typeof DashboardUnitsUnitIdEditRoute
}

const DashboardUnitsRouteChildren: DashboardUnitsRouteChildren = {
  DashboardUnitsUnitIdEditRoute: DashboardUnitsUnitIdEditRoute,
}

const DashboardUnitsRouteWithChildren = DashboardUnitsRoute._addFileChildren(
  DashboardUnitsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCoursesRoute: typeof DashboardCoursesRouteWithChildren
  DashboardExercisesRoute: typeof DashboardExercisesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardUnitsRoute: typeof DashboardUnitsRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCoursesRoute: DashboardCoursesRouteWithChildren,
  DashboardExercisesRoute: DashboardExercisesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardUnitsRoute: DashboardUnitsRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
