/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardUnitsRouteImport } from './routes/dashboard/units'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardQuizRouteImport } from './routes/dashboard/quiz'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard/courses'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardQuizIndexRouteImport } from './routes/dashboard/quiz/index'
import { Route as DashboardCoursesIndexRouteImport } from './routes/dashboard/courses/index'
import { Route as DashboardSettingsCustomizationRouteImport } from './routes/dashboard/settings/customization'
import { Route as DashboardSettingsAccountRouteImport } from './routes/dashboard/settings/account'
import { Route as DashboardQuizAddRouteImport } from './routes/dashboard/quiz/add'
import { Route as DashboardQuizQuizIdRouteImport } from './routes/dashboard/quiz/$quizId'
import { Route as DashboardCoursesAddRouteImport } from './routes/dashboard/courses/add'
import { Route as DashboardUnitsUnitIdEditRouteImport } from './routes/dashboard/units/$unitId/edit'
import { Route as DashboardCoursesCourseIdViewRouteImport } from './routes/dashboard/courses/$courseId.view'
import { Route as DashboardCoursesCourseIdUpdateRouteImport } from './routes/dashboard/courses/$courseId.update'
import { Route as DashboardCoursesCourseIdEditIndexRouteImport } from './routes/dashboard/courses/$courseId/edit/index'
import { Route as DashboardCoursesCourseIdEditCurriculumRouteImport } from './routes/dashboard/courses/$courseId/edit/curriculum'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUnitsRoute = DashboardUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizRoute = DashboardQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUsersRoute,
} as any)
const DashboardQuizIndexRoute = DashboardQuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardQuizRoute,
} as any)
const DashboardCoursesIndexRoute = DashboardCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCoursesRoute,
} as any)
const DashboardSettingsCustomizationRoute =
  DashboardSettingsCustomizationRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsAccountRoute =
  DashboardSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardQuizAddRoute = DashboardQuizAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DashboardQuizRoute,
} as any)
const DashboardQuizQuizIdRoute = DashboardQuizQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => DashboardQuizRoute,
} as any)
const DashboardCoursesAddRoute = DashboardCoursesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DashboardCoursesRoute,
} as any)
const DashboardUnitsUnitIdEditRoute =
  DashboardUnitsUnitIdEditRouteImport.update({
    id: '/$unitId/edit',
    path: '/$unitId/edit',
    getParentRoute: () => DashboardUnitsRoute,
  } as any)
const DashboardCoursesCourseIdViewRoute =
  DashboardCoursesCourseIdViewRouteImport.update({
    id: '/$courseId/view',
    path: '/$courseId/view',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)
const DashboardCoursesCourseIdUpdateRoute =
  DashboardCoursesCourseIdUpdateRouteImport.update({
    id: '/$courseId/update',
    path: '/$courseId/update',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)
const DashboardCoursesCourseIdEditIndexRoute =
  DashboardCoursesCourseIdEditIndexRouteImport.update({
    id: '/$courseId/edit/',
    path: '/$courseId/edit/',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)
const DashboardCoursesCourseIdEditCurriculumRoute =
  DashboardCoursesCourseIdEditCurriculumRouteImport.update({
    id: '/$courseId/edit/curriculum',
    path: '/$courseId/edit/curriculum',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/quiz': typeof DashboardQuizRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/units': typeof DashboardUnitsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/add': typeof DashboardCoursesAddRoute
  '/dashboard/quiz/$quizId': typeof DashboardQuizQuizIdRoute
  '/dashboard/quiz/add': typeof DashboardQuizAddRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/customization': typeof DashboardSettingsCustomizationRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/quiz/': typeof DashboardQuizIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/courses/$courseId/update': typeof DashboardCoursesCourseIdUpdateRoute
  '/dashboard/courses/$courseId/view': typeof DashboardCoursesCourseIdViewRoute
  '/dashboard/units/$unitId/edit': typeof DashboardUnitsUnitIdEditRoute
  '/dashboard/courses/$courseId/edit/curriculum': typeof DashboardCoursesCourseIdEditCurriculumRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/units': typeof DashboardUnitsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/courses/add': typeof DashboardCoursesAddRoute
  '/dashboard/quiz/$quizId': typeof DashboardQuizQuizIdRoute
  '/dashboard/quiz/add': typeof DashboardQuizAddRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/customization': typeof DashboardSettingsCustomizationRoute
  '/dashboard/courses': typeof DashboardCoursesIndexRoute
  '/dashboard/quiz': typeof DashboardQuizIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/courses/$courseId/update': typeof DashboardCoursesCourseIdUpdateRoute
  '/dashboard/courses/$courseId/view': typeof DashboardCoursesCourseIdViewRoute
  '/dashboard/units/$unitId/edit': typeof DashboardUnitsUnitIdEditRoute
  '/dashboard/courses/$courseId/edit/curriculum': typeof DashboardCoursesCourseIdEditCurriculumRoute
  '/dashboard/courses/$courseId/edit': typeof DashboardCoursesCourseIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/quiz': typeof DashboardQuizRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/units': typeof DashboardUnitsRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/add': typeof DashboardCoursesAddRoute
  '/dashboard/quiz/$quizId': typeof DashboardQuizQuizIdRoute
  '/dashboard/quiz/add': typeof DashboardQuizAddRoute
  '/dashboard/settings/account': typeof DashboardSettingsAccountRoute
  '/dashboard/settings/customization': typeof DashboardSettingsCustomizationRoute
  '/dashboard/courses/': typeof DashboardCoursesIndexRoute
  '/dashboard/quiz/': typeof DashboardQuizIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/courses/$courseId/update': typeof DashboardCoursesCourseIdUpdateRoute
  '/dashboard/courses/$courseId/view': typeof DashboardCoursesCourseIdViewRoute
  '/dashboard/units/$unitId/edit': typeof DashboardUnitsUnitIdEditRoute
  '/dashboard/courses/$courseId/edit/curriculum': typeof DashboardCoursesCourseIdEditCurriculumRoute
  '/dashboard/courses/$courseId/edit/': typeof DashboardCoursesCourseIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/courses'
    | '/dashboard/quiz'
    | '/dashboard/settings'
    | '/dashboard/units'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/courses/add'
    | '/dashboard/quiz/$quizId'
    | '/dashboard/quiz/add'
    | '/dashboard/settings/account'
    | '/dashboard/settings/customization'
    | '/dashboard/courses/'
    | '/dashboard/quiz/'
    | '/dashboard/users/'
    | '/dashboard/courses/$courseId/update'
    | '/dashboard/courses/$courseId/view'
    | '/dashboard/units/$unitId/edit'
    | '/dashboard/courses/$courseId/edit/curriculum'
    | '/dashboard/courses/$courseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/settings'
    | '/dashboard/units'
    | '/dashboard'
    | '/dashboard/courses/add'
    | '/dashboard/quiz/$quizId'
    | '/dashboard/quiz/add'
    | '/dashboard/settings/account'
    | '/dashboard/settings/customization'
    | '/dashboard/courses'
    | '/dashboard/quiz'
    | '/dashboard/users'
    | '/dashboard/courses/$courseId/update'
    | '/dashboard/courses/$courseId/view'
    | '/dashboard/units/$unitId/edit'
    | '/dashboard/courses/$courseId/edit/curriculum'
    | '/dashboard/courses/$courseId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/courses'
    | '/dashboard/quiz'
    | '/dashboard/settings'
    | '/dashboard/units'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/courses/add'
    | '/dashboard/quiz/$quizId'
    | '/dashboard/quiz/add'
    | '/dashboard/settings/account'
    | '/dashboard/settings/customization'
    | '/dashboard/courses/'
    | '/dashboard/quiz/'
    | '/dashboard/users/'
    | '/dashboard/courses/$courseId/update'
    | '/dashboard/courses/$courseId/view'
    | '/dashboard/units/$unitId/edit'
    | '/dashboard/courses/$courseId/edit/curriculum'
    | '/dashboard/courses/$courseId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/units': {
      id: '/dashboard/units'
      path: '/units'
      fullPath: '/dashboard/units'
      preLoaderRoute: typeof DashboardUnitsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz': {
      id: '/dashboard/quiz'
      path: '/quiz'
      fullPath: '/dashboard/quiz'
      preLoaderRoute: typeof DashboardQuizRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardUsersRoute
    }
    '/dashboard/quiz/': {
      id: '/dashboard/quiz/'
      path: '/'
      fullPath: '/dashboard/quiz/'
      preLoaderRoute: typeof DashboardQuizIndexRouteImport
      parentRoute: typeof DashboardQuizRoute
    }
    '/dashboard/courses/': {
      id: '/dashboard/courses/'
      path: '/'
      fullPath: '/dashboard/courses/'
      preLoaderRoute: typeof DashboardCoursesIndexRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/settings/customization': {
      id: '/dashboard/settings/customization'
      path: '/customization'
      fullPath: '/dashboard/settings/customization'
      preLoaderRoute: typeof DashboardSettingsCustomizationRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/account': {
      id: '/dashboard/settings/account'
      path: '/account'
      fullPath: '/dashboard/settings/account'
      preLoaderRoute: typeof DashboardSettingsAccountRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/quiz/add': {
      id: '/dashboard/quiz/add'
      path: '/add'
      fullPath: '/dashboard/quiz/add'
      preLoaderRoute: typeof DashboardQuizAddRouteImport
      parentRoute: typeof DashboardQuizRoute
    }
    '/dashboard/quiz/$quizId': {
      id: '/dashboard/quiz/$quizId'
      path: '/$quizId'
      fullPath: '/dashboard/quiz/$quizId'
      preLoaderRoute: typeof DashboardQuizQuizIdRouteImport
      parentRoute: typeof DashboardQuizRoute
    }
    '/dashboard/courses/add': {
      id: '/dashboard/courses/add'
      path: '/add'
      fullPath: '/dashboard/courses/add'
      preLoaderRoute: typeof DashboardCoursesAddRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/units/$unitId/edit': {
      id: '/dashboard/units/$unitId/edit'
      path: '/$unitId/edit'
      fullPath: '/dashboard/units/$unitId/edit'
      preLoaderRoute: typeof DashboardUnitsUnitIdEditRouteImport
      parentRoute: typeof DashboardUnitsRoute
    }
    '/dashboard/courses/$courseId/view': {
      id: '/dashboard/courses/$courseId/view'
      path: '/$courseId/view'
      fullPath: '/dashboard/courses/$courseId/view'
      preLoaderRoute: typeof DashboardCoursesCourseIdViewRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/courses/$courseId/update': {
      id: '/dashboard/courses/$courseId/update'
      path: '/$courseId/update'
      fullPath: '/dashboard/courses/$courseId/update'
      preLoaderRoute: typeof DashboardCoursesCourseIdUpdateRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/courses/$courseId/edit/': {
      id: '/dashboard/courses/$courseId/edit/'
      path: '/$courseId/edit'
      fullPath: '/dashboard/courses/$courseId/edit'
      preLoaderRoute: typeof DashboardCoursesCourseIdEditIndexRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/courses/$courseId/edit/curriculum': {
      id: '/dashboard/courses/$courseId/edit/curriculum'
      path: '/$courseId/edit/curriculum'
      fullPath: '/dashboard/courses/$courseId/edit/curriculum'
      preLoaderRoute: typeof DashboardCoursesCourseIdEditCurriculumRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
  }
}

interface DashboardCoursesRouteChildren {
  DashboardCoursesAddRoute: typeof DashboardCoursesAddRoute
  DashboardCoursesIndexRoute: typeof DashboardCoursesIndexRoute
  DashboardCoursesCourseIdUpdateRoute: typeof DashboardCoursesCourseIdUpdateRoute
  DashboardCoursesCourseIdViewRoute: typeof DashboardCoursesCourseIdViewRoute
  DashboardCoursesCourseIdEditCurriculumRoute: typeof DashboardCoursesCourseIdEditCurriculumRoute
  DashboardCoursesCourseIdEditIndexRoute: typeof DashboardCoursesCourseIdEditIndexRoute
}

const DashboardCoursesRouteChildren: DashboardCoursesRouteChildren = {
  DashboardCoursesAddRoute: DashboardCoursesAddRoute,
  DashboardCoursesIndexRoute: DashboardCoursesIndexRoute,
  DashboardCoursesCourseIdUpdateRoute: DashboardCoursesCourseIdUpdateRoute,
  DashboardCoursesCourseIdViewRoute: DashboardCoursesCourseIdViewRoute,
  DashboardCoursesCourseIdEditCurriculumRoute:
    DashboardCoursesCourseIdEditCurriculumRoute,
  DashboardCoursesCourseIdEditIndexRoute:
    DashboardCoursesCourseIdEditIndexRoute,
}

const DashboardCoursesRouteWithChildren =
  DashboardCoursesRoute._addFileChildren(DashboardCoursesRouteChildren)

interface DashboardQuizRouteChildren {
  DashboardQuizQuizIdRoute: typeof DashboardQuizQuizIdRoute
  DashboardQuizAddRoute: typeof DashboardQuizAddRoute
  DashboardQuizIndexRoute: typeof DashboardQuizIndexRoute
}

const DashboardQuizRouteChildren: DashboardQuizRouteChildren = {
  DashboardQuizQuizIdRoute: DashboardQuizQuizIdRoute,
  DashboardQuizAddRoute: DashboardQuizAddRoute,
  DashboardQuizIndexRoute: DashboardQuizIndexRoute,
}

const DashboardQuizRouteWithChildren = DashboardQuizRoute._addFileChildren(
  DashboardQuizRouteChildren,
)

interface DashboardSettingsRouteChildren {
  DashboardSettingsAccountRoute: typeof DashboardSettingsAccountRoute
  DashboardSettingsCustomizationRoute: typeof DashboardSettingsCustomizationRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsAccountRoute: DashboardSettingsAccountRoute,
  DashboardSettingsCustomizationRoute: DashboardSettingsCustomizationRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardUnitsRouteChildren {
  DashboardUnitsUnitIdEditRoute: typeof DashboardUnitsUnitIdEditRoute
}

const DashboardUnitsRouteChildren: DashboardUnitsRouteChildren = {
  DashboardUnitsUnitIdEditRoute: DashboardUnitsUnitIdEditRoute,
}

const DashboardUnitsRouteWithChildren = DashboardUnitsRoute._addFileChildren(
  DashboardUnitsRouteChildren,
)

interface DashboardUsersRouteChildren {
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardUsersRouteChildren: DashboardUsersRouteChildren = {
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardUsersRouteWithChildren = DashboardUsersRoute._addFileChildren(
  DashboardUsersRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCoursesRoute: typeof DashboardCoursesRouteWithChildren
  DashboardQuizRoute: typeof DashboardQuizRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardUnitsRoute: typeof DashboardUnitsRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCoursesRoute: DashboardCoursesRouteWithChildren,
  DashboardQuizRoute: DashboardQuizRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardUnitsRoute: DashboardUnitsRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
