
auth.token=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

defaults.org=anmol-ng
defaults.project=srvc

defaults.url=https://sentry.io/
