const env = process.env;
const isDev = env.EXPO_PUBLIC_MODE === "DEV" || __DEV__;

export const envs = Object.freeze({
	isDev,
	API_URL: isDev ? env.EXPO_PUBLIC_API_DEV_URL : env.EXPO_PUBLIC_API_PROD_URL,
	DOCS_URI: env.EXPO_PUBLIC_DOCS_URL,
	SENTRY: Object.freeze({
		DSN: env.EXPO_PUBLIC_SENTRY_DSN,
	}),
	META_URLS: Object.freeze({
		PLAYSTORE: env.EXPO_PUBLIC_METADATA_PLAYSTORE,
		APPSTORE: env.EXPO_PUBLIC_METADATA_APPSTORE,
		GITHUB: env.EXPO_PUBLIC_METADATA_GITHUB,

		ABOUT: env.EXPO_PUBLIC_METADATA_ABOUT_URL,
		TERMS: env.EXPO_PUBLIC_METADATA_TERMS_URL,
		SUPPORT: env.EXPO_PUBLIC_METADATA_SUPPORT_URL,
		POLICY: env.EXPO_PUBLIC_METADATA_POLICY_URL,
	}),
});
