name: CI

on:
  push:
    branches:
      - dev

jobs:
  preview_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shidil/cloudflare-workers-preview@v1
        id: preview_step
        with:
          cf_token: ${{ secrets.CF_API_TOKEN }}
          cf_account: ${{ secrets.CF_ACCOUNT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          domain: ainsa2279.workers.dev
          project_path: apps/app1
          build: |
            bun install
            bun run build
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"

      - name: Comment PR with preview links
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🚀 **Preview for this PR is live!**
            - **Server (Worker):** ${{ steps.preview_step.outputs.preview_url }}"
